### ISSUE TITLE
Version 1.0

### ISSUE THREAD

**Issue by zain-sohail** [OpenCOMPES/sed#462]
All changes are added to #437 before we finally merge to main

**Breaking changes**
- [x] #368
(Only issue with dask left to resolve. See #448)

- [x] #411
- [x] change binning factors from n to 2^n #173
 #451  
- [x] #404
 PR #451
- [x] #302
Ties in with #138 and pydantic models which were somewhat done in #330
- [x] FlashLoader refactor bugs
#459

**Not breaking but should be done**
- [x] Change version to v1.0
- [x] Update documentation workflow and #452

**Nice to haves**
- [x] #249 
- [ ] #268 which requires #457 first
- [x] #363

**Comment by rettigl** [comment]
@zain-sohail Some of the tutorial notebooks right now show some of the figures cut off, because the column width of the docs page is limited. This mostly affects the Flash tutorials. Could you fix this, i.e. limit the figure sizes? For possible sizes, look at the mpes examples.

**Comment by rettigl** [comment]
> Could you show me an example? The figures in v1 docs all look shrunk to me, and seem to fit.
This is how it looks like for me (Firefox):

![Image](https://github.com/user-attachments/assets/64d4d81a-97fa-45e3-abb1-b7e2ce7a9b8c)

**Comment by zain-sohail** [comment]
That's interesting:

<img width="810" alt="Image" src="https://github.com/user-attachments/assets/c6e2d59c-f78a-4511-8cbf-af8f2b451857" />

I checked on another laptop:

![Image](https://github.com/user-attachments/assets/fa7cf7f1-9a9b-4cc1-a0a7-cb883ce7f6b8)

Perhaps it has to do with resolution. I can set it to another aspect ratio but I am not sure which is universal.

**Comment by zain-sohail** [comment]
I checked with another monitor and indeed the issue you speak of arises. It seems that this is resolution dependent and I doubt we can achieve an ideal scenario for all monitors.

**Comment by rettigl** [comment]
> I checked with another monitor and indeed the issue you speak of arises. It seems that this is resolution dependent and I doubt we can achieve an ideal scenario for all monitors.

It only affects figures that are too wide. If we reduce the width for all figures to 8 or so, it does fit. See the mpes notebooks, where I did this already.

**Comment by rettigl** [comment]
V1 released
